### ISSUE TITLE
Find out how to have one Device Server type with multiple Device Classes

### ISSUE THREAD

**Issue by LJBD** [synchrotron-solaris/dev-solaris-adam#9]
We want to have only one DS called ADAM, but it should give us a possibility of creating devices belonging to several Device Classes. You have to find out how to do that in PyTango.

Note: there's a somewhat similar thing done [here](https://github.com/MaxIV-KitsControls/dev-maxiv-scope/blob/master/scopedevice/server.py). The difference is that we want to have a single script after installation. I suppose if you configure a `setup.py` so that it takes such a `run` method and creates a single entry point based on it.

**Comment by wkitka** [comment]
cpt-majkel (SHG, LandauSHG, RingSHG) and stanislaw47 (Valve, FastValve) added as assignees.

**Comment by LJBD** [comment]
A working example on how to do this can be found [here](https://github.com/LJBD/lib-tango-sample-device).
